# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prediction_debug_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 490, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 571, 541))
        self.label.setObjectName("label")
        self.pushButton_down = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_down.setGeometry(QtCore.QRect(670, 460, 71, 25))
        self.pushButton_down.setObjectName("pushButton_down")
        self.pushButton_up = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_up.setGeometry(QtCore.QRect(670, 400, 71, 25))
        self.pushButton_up.setObjectName("pushButton_up")
        self.pushButton_right = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_right.setGeometry(QtCore.QRect(720, 430, 71, 25))
        self.pushButton_right.setObjectName("pushButton_right")
        self.pushButton_left = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_left.setGeometry(QtCore.QRect(630, 430, 71, 25))
        self.pushButton_left.setObjectName("pushButton_left")
        self.pushButton_rotateClock = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_rotateClock.setGeometry(QtCore.QRect(720, 370, 71, 25))
        self.pushButton_rotateClock.setObjectName("pushButton_rotateClock")
        self.pushButton_counterRotate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_counterRotate.setGeometry(QtCore.QRect(630, 370, 71, 25))
        self.pushButton_counterRotate.setObjectName("pushButton_counterRotate")
        self.label_vel1 = QtWidgets.QLabel(self.centralwidget)
        self.label_vel1.setGeometry(QtCore.QRect(630, 270, 51, 17))
        self.label_vel1.setObjectName("label_vel1")
        self.label_vel2 = QtWidgets.QLabel(self.centralwidget)
        self.label_vel2.setGeometry(QtCore.QRect(630, 290, 67, 17))
        self.label_vel2.setObjectName("label_vel2")
        self.label_acc1 = QtWidgets.QLabel(self.centralwidget)
        self.label_acc1.setGeometry(QtCore.QRect(630, 310, 67, 17))
        self.label_acc1.setObjectName("label_acc1")
        self.label_vel2_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_vel2_3.setGeometry(QtCore.QRect(630, 330, 67, 17))
        self.label_vel2_3.setObjectName("label_vel2_3")
        self.textEdit_vel1 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_vel1.setGeometry(QtCore.QRect(680, 270, 91, 21))
        self.textEdit_vel1.setObjectName("textEdit_vel1")
        self.textEdit_vel2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_vel2.setGeometry(QtCore.QRect(680, 290, 91, 21))
        self.textEdit_vel2.setObjectName("textEdit_vel2")
        self.textEdit_acc1 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_acc1.setGeometry(QtCore.QRect(680, 310, 91, 21))
        self.textEdit_acc1.setObjectName("textEdit_acc1")
        self.textEdit_acc2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_acc2.setGeometry(QtCore.QRect(680, 330, 91, 21))
        self.textEdit_acc2.setObjectName("textEdit_acc2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Prediction debugger"))
        self.pushButton.setText(_translate("MainWindow", "Inference"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_down.setText(_translate("MainWindow", "Down"))
        self.pushButton_up.setText(_translate("MainWindow", "Up"))
        self.pushButton_right.setText(_translate("MainWindow", "Right"))
        self.pushButton_left.setText(_translate("MainWindow", "Left"))
        self.pushButton_rotateClock.setText(_translate("MainWindow", "cl_rot"))
        self.pushButton_counterRotate.setText(_translate("MainWindow", "count_rot"))
        self.label_vel1.setText(_translate("MainWindow", "Vel1"))
        self.label_vel2.setText(_translate("MainWindow", "Vel2"))
        self.label_acc1.setText(_translate("MainWindow", "Acc1"))
        self.label_vel2_3.setText(_translate("MainWindow", "Acc2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
